### ISSUE TITLE
Is it possible to play from an assetbundle?

### ISSUE THREAD

**Issue by anchpop** [rxlabz/audioplayer#12]
I was just wondering if that's a possibility, and if so, how?

That's for this very useful library, bu the way!

**Comment by anchpop** [comment]
I tried this:

`final result = await this.player.play(await rootBundle.loadString('assets/Ringtone-4.mp3'), isLocal: true);`


But I got this error:

```
E/flutter (19590): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (19590): FormatException: Bad UTF-8 encoding 0xff (at offset 279)
E/flutter (19590): #0      _Utf8Decoder.convert (dart:convert/utf.dart:568)
E/flutter (19590): #1      Utf8Decoder.convert (dart:convert/utf.dart:344)
E/flutter (19590): #2      Utf8Codec.decode (dart:convert/utf.dart:66)
E/flutter (19590): #3      CachingAssetBundle._fetchString (package:flutter/src/services/asset_bundle.dart:163:17)
E/flutter (19590): <asynchronous suspension>
E/flutter (19590): #4      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:155:50)
E/flutter (19590): #5      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:274)
E/flutter (19590): #6      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:155:27)
E/flutter (19590): #7      _AudioEntryState.play (/data/user/0/bz.rxla.audioplayer_example/cache/exampleUQQBYU/example/lib/main.dart:134:60)
E/flutter (19590): <asynchronous suspension>
E/flutter (19590): #8      _AudioEntryState.build.<anonymous closure> (/data/user/0/bz.rxla.audioplayer_example/cache/exampleUQQBYU/example/lib/main.dart:215:69)
E/flutter (19590): #9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:323:14)
E/flutter (19590): #10     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:375:30)
E/flutter (19590): #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (19590): #12     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (19590): #13     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
E/flutter (19590): #14     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (19590): #15     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter (19590): #16     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (19590): #17     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (19590): #18     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (19590): #19     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (19590): #20     _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:105)
E/flutter (19590): #21     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:63)```

**Comment by rxlabz** [comment]
Hi, it's possible to copy a file from assets to AppStorage : https://github.com/rxlabz/audioplayer/issues/5
