### ISSUE TITLE
run it under web, threw below exception

### ISSUE THREAD

**Issue by stoneLee81** [rxlabz/audioplayer#139]
_state == AudioPlayerState.PLAYING
is not true, null)
    at Object.throw_ [as throw] (http://localhost:61390/dart_sdk.js:4334:11)
    at StandardMethodCodec.decodeEnvelope (http://localhost:61390/packages/flutter/src/services/system_channels.dart.lib.js:780:19)
    at platform_channel.MethodChannel.new._invokeMethod (http://localhost:61390/packages/flutter/src/services/system_channels.dart.lib.js:943:32)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:61390/dart_sdk.js:37603:33
    at _RootZone.runUnary (http://localhost:61390/dart_sdk.js:37457:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:61390/dart_sdk.js:32441:29)
    at handleValueCallback (http://localhost:61390/dart_sdk.js:32988:49)
    at Function._propagateToListeners (http://localhost:61390/dart_sdk.js:33026:17)
    at _Future.new.[_completeWithValue] (http://localhost:61390/dart_sdk.js:32869:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:61390/dart_sdk.js:32891:35)
    at Object._microtaskLoop (http://localhost:61390/dart_sdk.js:37718:13)
    at _startMicrotaskLoop (http://localhost:61390/dart_sdk.js:37724:13)
    at http://localhost:61390/dart_sdk.js:33243:9Application finished.

flutter --version

Flutter 1.21.0-9.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision be9bc8cb39 (5 days ago) • 2020-08-18 09:46:08 -0700
Engine • revision 267070c17a
Tools • Dart 2.10.0 (build 2.10.0-7.2.beta)

**Comment by rafalzagoorski** [comment]
I have the same problem, anyone have the answer?

**Comment by DroidGar** [comment]
same problem here, any fix?

**Comment by jidogoon** [comment]
same problem when call play() again after player stopped.
