### ISSUE TITLE
app collapse when playing， occasionally suddenly

### ISSUE THREAD

**Issue by gateshibill** [rxlabz/audioplayer#157]
W/Choreographer(15953): Frame time is 17.409424 ms in the future! Check that graphics HAL is generating vsync timestamps using the correct timebase.
W/Choreographer(15953): Frame time is 16.27997 ms in the future! Check that graphics HAL is generating vsync timestamps using the correct timebase.
D/ViewRootImpl(15953): DisplayId = 0
I/MediaBrowserService(15953): No root for client com.android.bluetooth from service android.service.media.MediaBrowserService$ServiceBinder$1
D/AndroidRuntime(15953): Shutting down VM
E/AndroidRuntime(15953): FATAL EXCEPTION: main
E/AndroidRuntime(15953): Process: com.freejoy.music, PID: 15953
E/AndroidRuntime(15953): java.lang.RuntimeException: Unable to stop service bz.rxla.audioplayer.AudioplayerPlugin@40c9b0d: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.session.MediaSession.release()' on a null object reference
E/AndroidRuntime(15953): at android.app.ActivityThread.handleStopService(ActivityThread.java:4048)
E/AndroidRuntime(15953): at android.app.ActivityThread.access$1900(ActivityThread.java:233)
E/AndroidRuntime(15953): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1917)
E/AndroidRuntime(15953): at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15953): at android.os.Looper.loop(Looper.java:233)
E/AndroidRuntime(15953): at android.app.ActivityThread.main(ActivityThread.java:7225)
E/AndroidRuntime(15953): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15953): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
E/AndroidRuntime(15953): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)
E/AndroidRuntime(15953): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.session.MediaSession.release()' on a null object reference
E/AndroidRuntime(15953): at bz.rxla.audioplayer.AudioplayerPlugin.onDestroy(AudioplayerPlugin.java:199)
E/AndroidRuntime(15953): at android.app.ActivityThread.handleStopService(ActivityThread.java:4028)
E/AndroidRuntime(15953): ... 8 more
I/Process (15953): Sending signal. PID: 15953 SIG: 9
Lost connection to device.

AndroidManifest.xml
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>

**Comment by gateshibill** [comment]
This problem will occur when the Bluetooth switch of the mobile phone is switched,from close to open
