### ISSUE TITLE
Does audioplayer support living streaming audio

### ISSUE THREAD

**Issue by csbenjamin** [rxlabz/audioplayer#17]
In this case, the audio is sent with Transfer-Encoding: chunked and no Content-length. I am trying that and getting the following error:

    V/MediaPlayer-JNI( 5451): native_setup
    V/MediaPlayer( 5451): constructor
    V/MediaPlayer( 5451): setListener
    V/MediaPlayer-JNI( 5451): setAudioStreamType: 3
    V/MediaPlayer( 5451): MediaPlayer::setAudioStreamType
    V/MediaPlayer( 5451): setVideoSurfaceTexture
    V/MediaPlayer( 5451): prepare
    D/MediaHTTPConnection( 5451): setReadTimeOut =  30000ms
    D/MediaHTTPConnection( 5451): setReadTimeout with 30000ms
    I/System.out( 5451): (HTTPLog)-Static: isSBSettingEnabled false
    I/System.out( 5451): (HTTPLog)-Static: isSBSettingEnabled false
    I/MediaHTTPConnection( 5451): response code = 200
    V/MediaHTTPConnection( 5451): mTotalSize is -1
    V/MediaPlayer( 5451): message received msg=100, ext1=1, ext2=-2147483648
    E/MediaPlayer( 5451): error (1, -2147483648)
    V/MediaPlayer( 5451): signal application thread
    V/MediaPlayer( 5451): prepare complete - status=1
    D/AUDIO   ( 5451): media prepare ERROR
    W/System.err( 5451): java.io.IOException: Prepare failed.: status=0x1
    W/System.err( 5451): 	at android.media.MediaPlayer._prepare(Native Method)
    W/System.err( 5451): 	at android.media.MediaPlayer.prepare(MediaPlayer.java:1408)
    W/System.err( 5451): 	at bz.rxla.audioplayer.AudioplayerPlugin.play(AudioplayerPlugin.java:92)
    W/System.err( 5451): 	at bz.rxla.audioplayer.AudioplayerPlugin.onMethodCall(AudioplayerPlugin.java:44)
    W/System.err( 5451): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
    W/System.err( 5451): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:128)
    W/System.err( 5451): 	at android.os.MessageQueue.nativePollOnce(Native Method)
    W/System.err( 5451): 	at android.os.MessageQueue.next(MessageQueue.java:323)
    W/System.err( 5451): 	at android.os.Looper.loop(Looper.java:136)
    W/System.err( 5451): 	at android.app.ActivityThread.main(ActivityThread.java:6682)
    W/System.err( 5451): 	at java.lang.reflect.Method.invoke(Native Method)
    W/System.err( 5451): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
    W/System.err( 5451): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
    W/System.err( 5451): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
    V/MediaPlayer( 5451): getDuration_l
    E/MediaPlayer( 5451): Attempt to call getDuration in wrong state: mPlayer=0xc3869f40, mCurrentState=0
    V/MediaPlayer( 5451): message received msg=100, ext1=-38, ext2=0
    E/MediaPlayer( 5451): error (-38, 0)
    V/MediaPlayer( 5451): callback application
    V/MediaPlayer( 5451): back from callback
    V/MediaPlayer-JNI( 5451): getDuration: 0 (msec)
    V/MediaPlayer-JNI( 5451): start
    V/MediaPlayer( 5451): start
    E/MediaPlayer( 5451): start called in state 0, mPlayer(0xc3869f40)
    V/MediaPlayer( 5451): message received msg=100, ext1=-38, ext2=0
    E/MediaPlayer( 5451): error (-38, 0)
    V/MediaPlayer( 5451): callback application
    V/MediaPlayer( 5451): back from callback
    E/MediaPlayer( 5451): Error (-38,0)
    V/MediaPlayer-JNI( 5451): stop
    V/MediaPlayer( 5451): stop
    E/MediaPlayer( 5451): stop called in state 0, mPlayer(0xc3869f40)
    V/MediaPlayer( 5451): message received msg=100, ext1=-38, ext2=0
    E/MediaPlayer( 5451): error (-38, 0)
    V/MediaPlayer( 5451): callback application
    V/MediaPlayer( 5451): back from callback
    V/MediaPlayer-JNI( 5451): release
    V/MediaPlayer( 5451): setListener
    V/MediaPlayer( 5451): disconnect
    V/MediaPlayer( 5451): destructor
    V/MediaPlayer( 5451): disconnect
    I/Choreographer( 5451): Skipped 349 frames!  The application may be doing too much work on its main thread.
    W/MediaPlayer( 5451): mediaplayer went away with unhandled events
    W/MediaPlayer( 5451): mediaplayer went away with unhandled events

**Comment by csbenjamin** [comment]
It supports. It was a problem with my source streaming. When I tested with another streaming it works as expected.
