### ISSUE TITLE
Local file

### ISSUE THREAD

**Issue by twistedinferno** [rxlabz/audioplayer#25]
I have tried to play a local file but couldn't seem to get this working.  Is this supported?

I tried something like the following
`await audioPlayer.play('assets/sloths.mp3', isLocal: true);`
with the assets directory directly off my main flutter directory

_(massive caveat: I am only two days old with flutter and dart!  Keep up the good work 👍 )_

Errors
E/ExtMediaPlayer-JNI(11260): env->IsInstanceOf fails
E/MediaPlayer-JNI(11260): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/ExtMediaPlayer-JNI(11260): env->IsInstanceOf fails
E/MediaPlayer-JNI(11260): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
W/System.err(11260): java.io.IOException: setDataSource failed.
W/System.err(11260): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1095)
W/System.err(11260): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1041)

**Comment by twistedinferno** [comment]
#12
