### ISSUE TITLE
Requires SDK version >=1.8.0 <2.0.0, version solving failed.

### ISSUE THREAD

**Issue by IAmKio** [rxlabz/audioplayer#56]
Hi there,

I'm currently getting the error:
```
Because the app depends on audioplayer any which requires SDK version >=1.8.0 <2.0.0, version solving failed.
pub get failed (1)
exit code 1
```
When adding:  ` audioplayer:`  to my `pubspec.yaml`.

FYI, my current Dart version:

`The current Dart SDK version is 2.1.0-dev.1.0.flutter-69fce633b7` - which obviously explains the message above, however is it possible to have the SDK requirements updated?

Thanks!

**Comment by IAmKio** [comment]
Just FYI - changing the `pubspec.yaml` to `sdk: ">=1.19.0 <3.0.0"` works. There's also another bug that i have referenced [here](https://github.com/luanpotter/audioplayer/issues/34) in a fork of this project in regards to Firebase AdMob and an iOS symbol clash. I'll open a PR for that and link it here for future use.

**Comment by marcosfons** [comment]
I'm get the same error using audioplayer. But your solution doesn't work for me. I get this error:

`Because project depends on flutter any from sdk which doesn't exist (unknown SDK ">=1.19.0 <3.0.0"), version solving failed.`

What I'm doing wrong?

**Comment by tmcalves** [comment]
@IAmKio tried your forks code and got the error running for iOS

> Running pod install...
CocoaPods' output:
↳
      Preparing
    
    Analyzing dependencies
    
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    
    Finding Podfile changes
      A audioplayer2
      - Flutter
      - shared_preferences
      - url_launcher
    
    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `audioplayer2` from `.symlinks/plugins/audioplayer2/ios`
    [!] No podspec found for `audioplayer2` in `.symlinks/plugins/audioplayer2/ios`
    
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:85:in `titled_section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:697:in `fetch_external_source'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:673:in `block (2 levels) in fetch_external_sources'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:672:in `each'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:672:in `block in fetch_external_sources'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:671:in `fetch_external_sources'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:85:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `<main>'
Error output from CocoaPods:
↳
    
    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Error running pod install
Error launching application on iPhone X.

Any idea what can be wrong there?

**Comment by xioxu** [comment]
I got the same issue.
@IAmKio , which 'pubspec.yam' is you changed? the file of audioplayer? but I didn't find it in my project.

**Comment by adrianczuczka** [comment]
Any update on this?

**Comment by yusuf-topou** [comment]
This package has been forked see[https://pub.dartlang.org/packages/audioplayers]( https://pub.dartlang.org/packages/audioplayers). There might be breaking changes.
Hope it helps

**Comment by shubhamhackz** [comment]
First try upgrading your `audioplayer` plugin version if a new version is available, if not then try doing what @IAmKio had suggested.

**Comment by GopinathKaliappan** [comment]
Try the below commands.

```
flutter channel dev
flutter upgrade
```

Will Solve the issue.

**Comment by shixiaoquan** [comment]
> Try the below commands.
> 
> ```
> flutter channel dev
> flutter upgrade
> ```
> Will Solve the issue.

Yes I tried, it worked for me

**Comment by realsign** [comment]
i have same problem cant get the dependency. i have latest sdk 2.3.0-dev

**Comment by Sanaebadi97** [comment]
```
  geolocation: ^0.2.1

environment:
  sdk: ">=2.2.0 <3.0.0"
```


```
Running "flutter pub get" in one_menu...                        
The current Dart SDK version is 2.3.2-dev.0.0.flutter-b080e7c97a.

Because one_menu depends on geolocation >=0.1.1 which requires SDK version <2.0.0, version solving failed.


pub get failed (1)
Process finished with exit code 1
```

**Comment by Tareque16** [comment]
The solution is in your plugins pubspec.yaml. Just change the environment sdk setup please

environment:
sdk: ">=2.0.0-dev.58.0 <3.0.0"

**Comment by Tareque2208** [comment]
> ```
>   geolocation: ^0.2.1
> 
> environment:
>   sdk: ">=2.2.0 <3.0.0"
> ```
> 
> any update? I have the same problem with this config
> 
> ```
> Running "flutter pub get" in one_menu...                        
> The current Dart SDK version is 2.3.2-dev.0.0.flutter-b080e7c97a.
> 
> Because one_menu depends on geolocation >=0.1.1 which requires SDK version <2.0.0, version solving failed.
> 
> 
> pub get failed (1)
> Process finished with exit code 1
> ```

did you find the solution @Sanaebadi97

**Comment by jain-shreyansh** [comment]
Any updates?

**Comment by Arjunraj-k** [comment]
```
The current Flutter SDK version is 1.9.1+hotfix.6.

Because app depends on firebase_auth >=0.15.1+1 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.
Running "flutter pub get" in app...
pub get failed (1)
```

same problem here

**Comment by thanhbinh84** [comment]
Your flutter is old. Try to upgrade and run again 
`flutter upgrade`

**Comment by david-ssantos** [comment]
Thanks. It work for me!

**Comment by ashudrupalchamp** [comment]
I am getting this.
Please help
Thanks in advance
`
The current Dart SDK version is 2.8.4.

Because app depends on flutter_markdown ^0.1.0 which requires SDK version >=1.19.0 <2.0.0, version solving failed.
pub get failed (1; Because instastore depends on flutter_markdown ^0.1.0 which requires SDK version >=1.19.0 <2.0.0, version solving failed.)`

**Comment by ashudrupalchamp** [comment]
> Your flutter is old. Try to upgrade and run again
> `flutter upgrade`

Doesn't work for me

**Comment by Sadat-Aerafin** [comment]
> 
> Yes I tried, it worked for me.
Thank you .
