### ISSUE TITLE
How to play from assets in flutter app

### ISSUE THREAD

**Issue by anuranBarman** [rxlabz/audioplayer#57]
I have added a mp3 file in asset and trying to play it as local file from the play method. But it is not getting played. what can be the reason?

**Comment by cnqiuxue** [comment]
me too.
W/MediaPlayer(29597): See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
W/bz.rxla.flutter/audio(29597): Invalid DataSource
W/bz.rxla.flutter/audio(29597): java.io.IOException: setDataSource failed.
W/bz.rxla.flutter/audio(29597): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1187)
W/bz.rxla.flutter/audio(29597): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1160)
W/bz.rxla.flutter/audio(29597): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1127)
W/bz.rxla.flutter/audio(29597): 	at bz.rxla.audioplayer.AudioplayerPlugin.play(AudioplayerPlugin.java:108)
W/bz.rxla.flutter/audio(29597): 	at bz.rxla.audioplayer.AudioplayerPlugin.onMethodCall(AudioplayerPlugin.java:46)
W/bz.rxla.flutter/audio(29597): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
W/bz.rxla.flutter/audio(29597): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
W/bz.rxla.flutter/audio(29597): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/bz.rxla.flutter/audio(29597): 	at android.os.MessageQueue.next(MessageQueue.java:325)
W/bz.rxla.flutter/audio(29597): 	at android.os.Looper.loop(Looper.java:142)
W/bz.rxla.flutter/audio(29597): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
W/bz.rxla.flutter/audio(29597): 	at java.lang.reflect.Method.invoke(Native Method)
W/bz.rxla.flutter/audio(29597): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
W/bz.rxla.flutter/audio(29597): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by maheshmnj** [comment]
somebody help solve this issue please

**Comment by BwesShr** [comment]
same here... anyone know how

**Comment by xiaolongwuhpu** [comment]
- the real path is assets/xxx.ogg

- `if  (mMusicUrl.startsWith('assets')) 
      mMusicUrl =  mMusicUrl.replaceFirst("assets/", "asset:///flutter_assets/assets/");`


hope this helps

**Comment by serkandyck** [comment]
https://stackoverflow.com/questions/51901558/play-a-custom-sound-in-flutter

**Comment by shinriyo** [comment]
I guess ogg doesn't support..
