### ISSUE TITLE
the plugin is not working (even in the provided example !)

### ISSUE THREAD

**Issue by terryBaz** [rxlabz/audioplayer#81]
- I could not run the package in my app, that is what I am getting:
```
V/ViewRootImpl( 8772): debug enqueueInputEvent: event = MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=669.07074, y[0]=88.93052, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=65959062, downTime=65959062, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 com.example.adliss/com.example.adliss.MainActivity,ident = 0}
V/ViewRootImpl( 8772): debug enqueueInputEvent: event = MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=669.07074, y[0]=88.93052, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=65959166, downTime=65959062, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 com.example.adliss/com.example.adliss.MainActivity,ident = 0}
E/MethodChannel#bz.rxla.flutter/audio( 8772): Failed to handle method call
E/MethodChannel#bz.rxla.flutter/audio( 8772): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
E/MethodChannel#bz.rxla.flutter/audio( 8772): 	at bz.rxla.audioplayer.AudioplayerPlugin.onMethodCall(AudioplayerPlugin.java:46)
E/MethodChannel#bz.rxla.flutter/audio( 8772): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#bz.rxla.flutter/audio( 8772): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#bz.rxla.flutter/audio( 8772): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#bz.rxla.flutter/audio( 8772): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#bz.rxla.flutter/audio( 8772): 	at android.os.MessageQueue.next(MessageQueue.java:328)
E/MethodChannel#bz.rxla.flutter/audio( 8772): 	at android.os.Looper.loop(Looper.java:148)
E/MethodChannel#bz.rxla.flutter/audio( 8772): 	at android.app.ActivityThread.main(ActivityThread.java:6269)
E/MethodChannel#bz.rxla.flutter/audio( 8772): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#bz.rxla.flutter/audio( 8772): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
E/MethodChannel#bz.rxla.flutter/audio( 8772): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
E/flutter ( 8772): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference, null)
E/flutter ( 8772): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 8772): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 8772): <asynchronous suspension>
E/flutter ( 8772): #2      AudioPlayer.play (package:audioplayer/audioplayer.dart:47:22)
E/flutter ( 8772): <asynchronous suspension>
E/flutter ( 8772): #3      _ShowPageState.play (package:adliss/pages/show_page.dart:52:23)
E/flutter ( 8772): <asynchronous suspension>
E/flutter ( 8772): #4      _ShowPageState.build.<anonymous closure> (package:adliss/pages/show_page.dart:136:28)
E/flutter ( 8772): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter ( 8772): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter ( 8772): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
E/flutter ( 8772): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 8772): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter ( 8772): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:369:9)
E/flutter ( 8772): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 8772): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter ( 8772): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
E/flutter ( 8772): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter ( 8772): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter ( 8772): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 8772): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter ( 8772): #18     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 8772): #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 8772): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 8772): #21     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter ( 8772): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
```
- I also tried the example that you provide, the output:
```
Launching lib\main.dart on PGN528 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device PGN528...
D/GraphicBuffer( 9336): register, handle(0x75e16dbe80) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
D/OpenGLRenderer( 9336): ProgramCache.generateProgram: 34359738369
I/SurfaceView( 9336): updateWindow -- setFrame, this = io.flutter.view.FlutterView{68da120 VFE...... .F...... 0,0-720,1280}
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=182.74619, y[0]=479.6253, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=66226818, downTime=66226818, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=182.74619, y[0]=479.6253, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=66226875, downTime=66226818, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
D/AudioSystem( 9336): getIoDescriptor: ioHandle = 13, index = -2, mIoDescriptors = 0x75e573b550
D/AudioSystem( 9336): getIoDescriptor: ioHandle = 21, index = -2, mIoDescriptors = 0x75e573b550
D/MediaPlayer( 9336): Don't notify duration to bz.rxla.audioplayerexample!
D/MediaHTTPConnection( 9336): disconnect finish
D/NetworkSecurityConfig( 9336): No Network Security Config specified, using platform default
D/libc-netbsd( 9336): getaddrinfo: www.rxlabz.com get result from proxy gai_error = 0
I/System.out( 9336): [socket][0] connection www.rxlabz.com/217.70.184.50:80;LocalPort=-1(30000)
D/        ( 9336): [Posix_connect Debug]Process bz.rxla.audioplayerexample :80 
D/GraphicBuffer( 9336): register, handle(0x75deb35740) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
I/System.out( 9336): [socket][/192.168.1.4:49620] connected
I/System.out( 9336): [OkHttp] sendRequest>>
I/System.out( 9336): [OkHttp] sendRequest<<
D/libc-netbsd( 9336): getaddrinfo: rxlabz.com get result from proxy gai_error = 0
I/System.out( 9336): [socket][1] connection rxlabz.com/151.101.65.195:443;LocalPort=-1(30000)
D/        ( 9336): [Posix_connect Debug]Process bz.rxla.audioplayerexample :443 
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = KeyEvent { action=ACTION_UP, keyCode=KEYCODE_VOLUME_UP, scanCode=115, metaState=0, flags=0x8, repeatCount=0, eventTime=66237273, downTime=66237043, deviceId=9, source=0x101 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = KeyEvent { action=ACTION_UP, keyCode=KEYCODE_VOLUME_UP, scanCode=115, metaState=0, flags=0x8, repeatCount=0, eventTime=66237826, downTime=66237581, deviceId=9, source=0x101 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
I/System.out( 9336): [socket][/192.168.1.4:39623] connected
D/NativeCrypto( 9336): ssl=0x75faa51140 NativeCrypto_SSL_do_handshake fd=0x75e958d7d8 shc=0x75e958d7dc timeout_millis=60000 client_mode=1 npn=0x0
D/NativeCrypto( 9336): ssl=0x75faa51140 info_callback calling handshakeCompleted
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = KeyEvent { action=ACTION_UP, keyCode=KEYCODE_VOLUME_UP, scanCode=115, metaState=0, flags=0x8, repeatCount=0, eventTime=66238259, downTime=66238104, deviceId=9, source=0x101 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
D/NativeCrypto( 9336): ssl=0x75faa51140 cert_verify_callback => 1
I/art     ( 9336): Enter while loop.
D/NativeCrypto( 9336): ssl=0x75faa51140 NativeCrypto_SSL_get_certificate => NULL
I/System.out( 9336): [OkHttp] sendRequest>>
I/System.out( 9336): [OkHttp] sendRequest<<
V/InputMethodManager( 9336): onWindowFocus: io.flutter.view.FlutterView{68da120 VFE...... .F...... 0,0-720,1280} softInputMode=16 first=false flags=#81810100
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=525.27045, y[0]=1041.1865, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x2, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=66245082, downTime=66245082, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=525.27045, y[0]=1041.1865, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x2, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=66245128, downTime=66245082, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
D/NativeCrypto( 9336): ssl=0x75faa51140 info_callback calling handshakeCompleted
D/MediaHTTPConnection( 9336): mTotalSize=-1
D/MediaHTTPConnection( 9336): teardownConnection
I/System.out( 9336): Wrong owner. Perhaps a late disconnect
D/MediaHTTPConnection( 9336): disconnect finish
E/MediaPlayer( 9336): error (1, -2147483648)
D/MediaPlayer( 9336): handleMessage msg:(100, 1, -2147483648)
E/MediaPlayer( 9336): Error (1,-2147483648)
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=201.71983, y[0]=415.67526, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=66250933, downTime=66250933, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
D/GraphicBuffer( 9336): register, handle(0x75ded78b80) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=201.71983, y[0]=415.67526, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=66250990, downTime=66250933, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
E/MediaPlayer( 9336): start called in state 0, mPlayer(0x75e56953c0)
E/MediaPlayer( 9336): error (-38, 0)
E/MediaPlayer( 9336): Attempt to call getDuration in wrong state: mPlayer=0x75e56953c0, mCurrentState=0
E/MediaPlayer( 9336): error (-38, 0)
D/MediaPlayer( 9336): handleMessage msg:(100, -38, 0)
E/MediaPlayer( 9336): Error (-38,0)
D/MediaPlayer( 9336): handleMessage msg:(100, -38, 0)
E/MediaPlayer( 9336): Error (-38,0)
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=523.27325, y[0]=893.3021, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=66254060, downTime=66254060, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=523.27325, y[0]=893.3021, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=66254152, downTime=66254060, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
E/MethodChannel#bz.rxla.flutter/audio( 9336): Failed to handle method call
E/MethodChannel#bz.rxla.flutter/audio( 9336): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
E/MethodChannel#bz.rxla.flutter/audio( 9336): 	at bz.rxla.audioplayer.AudioplayerPlugin.onMethodCall(AudioplayerPlugin.java:46)
E/MethodChannel#bz.rxla.flutter/audio( 9336): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#bz.rxla.flutter/audio( 9336): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#bz.rxla.flutter/audio( 9336): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#bz.rxla.flutter/audio( 9336): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#bz.rxla.flutter/audio( 9336): 	at android.os.MessageQueue.next(MessageQueue.java:328)
E/MethodChannel#bz.rxla.flutter/audio( 9336): 	at android.os.Looper.loop(Looper.java:148)
E/MethodChannel#bz.rxla.flutter/audio( 9336): 	at android.app.ActivityThread.main(ActivityThread.java:6269)
E/MethodChannel#bz.rxla.flutter/audio( 9336): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#bz.rxla.flutter/audio( 9336): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
E/MethodChannel#bz.rxla.flutter/audio( 9336): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
E/flutter ( 9336): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference, null)
E/flutter ( 9336): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 9336): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 9336): <asynchronous suspension>
E/flutter ( 9336): #2      AudioPlayer.play (package:audioplayer/audioplayer.dart:47:22)
E/flutter ( 9336): <asynchronous suspension>
E/flutter ( 9336): #3      _AudioAppState._playLocal (package:audioplayer_example/main.dart:95:23)
E/flutter ( 9336): <asynchronous suspension>
E/flutter ( 9336): #4      _AudioAppState.build.<anonymous closure> (package:audioplayer_example/main.dart:173:48)
E/flutter ( 9336): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter ( 9336): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter ( 9336): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
E/flutter ( 9336): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 9336): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter ( 9336): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:369:9)
E/flutter ( 9336): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 9336): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter ( 9336): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
E/flutter ( 9336): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter ( 9336): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter ( 9336): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 9336): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter ( 9336): #18     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 9336): #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 9336): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 9336): #21     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter ( 9336): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
E/flutter ( 9336): 
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=184.74342, y[0]=416.67447, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=66256388, downTime=66256388, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
V/ViewRootImpl( 9336): debug enqueueInputEvent: event = MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=184.74342, y[0]=416.67447, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=66256457, downTime=66256388, deviceId=2, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{5609823 bz.rxla.audioplayerexample/bz.rxla.audioplayerexample.MainActivity,ident = 0}
E/MediaPlayer( 9336): start called in state 0, mPlayer(0x75e56953c0)
E/MediaPlayer( 9336): error (-38, 0)
E/MediaPlayer( 9336): Attempt to call getDuration in wrong state: mPlayer=0x75e56953c0, mCurrentState=0
E/MediaPlayer( 9336): error (-38, 0)
D/MediaPlayer( 9336): handleMessage msg:(100, -38, 0)
E/MediaPlayer( 9336): Error (-38,0)
D/MediaPlayer( 9336): handleMessage msg:(100, -38, 0)
E/MediaPlayer( 9336): Error (-38,0)

```

**Comment by Artemusp** [comment]
Same problem with: Attempt to call getDuration in wrong state.

**Comment by Amberon** [comment]
Another example:
```
E/MediaPlayerNative(17397): start called in state 0, mPlayer(0x7b45761b00)
E/MediaPlayerNative(17397): error (-38, 0)
E/MediaPlayerNative(17397): Attempt to call getDuration in wrong state: mPlayer=0x7b45761b00, mCurrentState=0
E/MediaPlayerNative(17397): error (-38, 0)
E/MediaPlayer(17397): Error (-38,0)
E/MediaPlayer(17397): Error (-38,0)
I/flutter (17397): PLAYING 124
```
I don't even need duration, it's a second-length file
